### ISSUE TITLE
Front-end code cleanup

### ISSUE THREAD

**Issue by javathunderman** [Nomikxyz/pants-on-fire#1]
I now have a bit more free time so I'd like to get this project cleaned up and running properly. 

At the moment, most of the code in this project is forked from nomikxyz/annoying-machine, including a hacky react.js situation that uses hard-coded HTML rather than a viewing engine like pug or ejs. I'd like to scrap the existing design and either create a new interface or recreate it in one of these frameworks. 

Thoughts @AJDev77 @ReishiRamzi @cheyennenoel ?

**Comment by cheyennenoel** [comment]
Gah forgot all about this! Literally about to start @ Hack Reactor for the summer (my time available to work on this will rapidly grow from infinity to 0, just as my ability to be totally useless at it will go from infinity to 0)

🤔 also there was some issue with the domain name? @ramzi?

I’m super down to spend the handful of hours to get this not-stupid... but I also won’t have the brains to help with that process without serious hand-holding until a few weeks from now (sorry—I’m frustrated by my ineptitude too)

That said, I’m about to be in SF @ Hack Reactor’s downtown campus for a few weeks, so if you have requests/questions/smellygrosscodebaseissues ...I’ll be here, with caffeine + nerds + MacBooks for a short while. Ask now or forever hold your peace.

@brilliant HS students that will replace us ASAP, Ramzi?

**Comment by javathunderman** [comment]
Also worth pinging @acontz and @faizaand while I'm at it.

**Comment by javathunderman** [comment]
@cheyennenoel We can configure the fake.news domain and point it at our VPS, it might be more efficient than finding a separate hosting situation for it. We also have Cloudflare configured on our main site and we could apply it to that domain; that should help keep out those pesky bots and hax0rs.

**Comment by javathunderman** [comment]
Update: latest commit adds basic ML functionality. Still training the model though.

**Comment by javathunderman** [comment]
OK - the ML backend and frontend have been unified! The model still isn't great, and it's not very reproducible, but it works on my machine.™
